<?php
/**
 * @file
 * Code for the lightning_fpp feature.
 */

include_once 'lightning_fpp.features.inc';
include_once 'lightning_fpp.widgets.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_fpp_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_fpp enabled ' . $component . ' component');
}

/**
 * Implements hook_entity_info_alter().
 */
function lightning_fpp_entity_info_alter(&$entity_info) {

  // Add our custom FPP types.
  $fpp_types = _lightning_fpp_fpp_types();
  foreach ($fpp_types as $type => $info) {
    $entity_info['fieldable_panels_pane']['bundles'][$type] = array(
      'label' => t('Add @title', array('@title' => $info['title'])),
      'pane category' => t('Custom'),
      'pane top level' => TRUE,
      'pane icon' => drupal_get_path('module', 'lightning_fpp') . '/images/' . $info['icon'],
      'admin' => array(
        'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
        'bundle argument' => 4,
        'real path' => 'admin/structure/fieldable-panels-panes/manage/' . $info['path'],
        'access arguments' => array('administer fieldable panels panes'),
      ),
    );
  }

}

