<?php
/**
 * @file
 * Code for the lightning_metatags feature.
 */

include_once 'lightning_metatags.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_metatags_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_metatags enabled ' . $component . ' component');
}

/**
 * Implements hook_entity_info_alter().
 */
function lightning_metatags_entity_info_alter(&$entity_info) {

  // Alternate Preview view mode for files.
  $entity_info['file']['view modes']['alt_preview'] = array(
    'label' => t('Alternate Preview'),
    'custom settings' => TRUE,
  );

}

