<?php
/**
 * @file
 * Code for the curate_content feature.
 */

include_once 'curate_content.features.inc';


/**
 *  Implements hook_post_features_enable_feature().
 */
function curate_content_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'curate_content enabled ' . $component . ' component');
}

/**
 * Implements hook_entity_info_alter().
 */
function curate_content_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['alternate'] = array(
    'label' => t('Alternate'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['thumbnail'] = array(
    'label' => t('Thumbnail'),
    'custom settings' => TRUE,
  );
}

