<?php
/**
 * @file
 * Code for the lightning_sps feature.
 */

include_once 'lightning_sps.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_sps_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_sps enabled ' . $component . ' component');
}

/**
 * Implements hook_field_widget_form_alter().
 */
function lightning_sps_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['overwrite']) && $element['overwrite']['#title'] == t('Remove collection from previous revision')) {
    $element['overwrite']['#default_value'] = 1;
  }
}

