<?php
/**
 * @file
 * Code for the lightning_roles feature.
 */

include_once 'lightning_roles.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_roles_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_roles enabled ' . $component . ' component');
}

/**
 * Implements hook_behat_info().
 */
function lightning_roles_behat_info() {
  $info = array(
    'paths' => array(
      'features' => 'features',
    ),
  );
  return $info;
}

