<?php
/**
 * @file
 * Code for the lightning_wysiwyg feature.
 */

include_once 'lightning_wysiwyg.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_wysiwyg_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_wysiwyg enabled ' . $component . ' component');
}

/**
 *  Implements hook_post_features_rebuild().
 */
function lightning_wysiwyg_post_features_rebuild($component) {
  // Revert CKEditor profiles as they were rebuilt before all filters
  // had finished rebuilding (Features a-z index logic bug).
  if ($component == 'filter') {
    features_revert(array('lightning_wysiwyg' => array('ckeditor_profile')));
  }
}

/**
 * Implements hook_behat_info().
 */
function lightning_wysiwyg_behat_info() {
  $info = array(
    'paths' => array(
      'features' => 'features',
    ),
  );

  return $info;
}

/**
 * Implements hook_entity_embed_alter().
 */
function lightning_wysiwyg_entity_embed_alter(&$build, $entity, $context) {
  // Remove the contextual links on all entites that provide them.
  if (isset($build['#contextual_links'])) {
    unset($build['#contextual_links']);
  }
}
