<?php
/**
 * @file
 * Code for the lightning_moderation moderation feature.
 */

include_once 'lightning_moderation.features.inc';

/**
 * Implements hook_migrate_api().
 */
function lightning_moderation_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'lightning' => array(
        'title' => t('Lightning'),
      ),
    ),
    'migrations' => array(
      'LightningModerationNodes' => array('class_name' => 'LightningModerationNodes', 'group_name' => 'lightning'),
    ),
  );
  return $api;
}

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_moderation_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_moderation enabled ' . $component . ' component');
}

/**
 * Implements hook_behat_info().
 */
function lightning_moderation_behat_info() {
  $info = array(
    'paths' => array(
      'features' => 'features',
    ),
  );

  return $info;
}
