<?php
/**
 * @file
 * Code for the lightning_moderation moderation feature.
 */

include_once 'lightning_moderation.features.inc';

/**
 * Implements hook_migrate_api().
 */
function lightning_moderation_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'lightning' => array(
        'title' => t('Lightning'),
      ),
    ),
    'migrations' => array(
      'LightningModerationNodes' => array('class_name' => 'LightningModerationNodes', 'group_name' => 'lightning'),
    ),
  );
  return $api;
}

/**
 * Implements hook_behat_info().
 */
function lightning_moderation_behat_info() {
  $info = array(
    'paths' => array(
      'features' => 'features',
    ),
  );

  return $info;
}

/**
 * Implements hook_block_info_alter().
 */
function lightning_moderation_block_info_alter(&$blocks, $theme, $code_blocks) {
  // Check for offcanvas region.
  $regions = system_region_list($theme);
  if (isset($regions['offcanvas'])) {
    // Move Workbench Moderation Block to offcanvas.
    $blocks['workbench']['block']['region'] = 'offcanvas';
  }
}

