<?php
/**
 * @file
 * Code for the lightning_letterbox feature.
 */

include_once 'lightning_letterbox.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function lightning_admin_entity_info_alter(&$entity_info) {
  // Alternate Preview view mode for files.
  $entity_info['file']['view modes']['alt_preview'] = array(
    'label' => t('Alternate Preview'),
    'custom settings' => TRUE,
  );
}
