<?php
/**
 * @file
 * Code for the lightning_panels feature.
 */

include_once 'lightning_panels.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function lightning_panels_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'lightning_panels enabled ' . $component . ' component');
}

/**
 * Implements hook_pre_features_rebuild().
 */
function lightning_panels_pre_features_rebuild($component) {
  if ($component == 'user_permission') {
    drupal_static_reset('panelizer_entity_plugin_get_handler');
  }
}
