<?php
/**
 * @file
 * Code for the assemble_letterbox feature.
 */

include_once 'assemble_letterbox.features.inc';

/**
 *  Implements hook_post_features_enable_feature().
 */
function assemble_letterbox_post_features_enable_feature($component) {
  // Log components as they are enabled.
  watchdog('component', 'assemble_letterbox enabled ' . $component . ' component');
}

/**
 * Implements hook_entity_info_alter().
 */
function assemble_admin_entity_info_alter(&$entity_info) {
  // Alternate Preview view mode for files.
  $entity_info['file']['view modes']['alt_preview'] = array(
    'label' => t('Alternate Preview'),
    'custom settings' => TRUE,
  );
}

